#!/usr/bin/env python3
"""
traduccion_lesiones.py
-------------------------
Diccionario de traduccion ingles->espanol para los tipos de lesion tal
cual los publica Transfermarkt. Solo son traducciones de vocabulario medico
estandar (no interpretacion ni diagnostico) -- si un tipo de lesion no esta
en el diccionario, se debe mostrar el texto original en ingles en vez de
adivinar una traduccion.

Usado por agregar_perfiles_jugador.py.
"""

TRADUCCION_LESION = {
    "unknown injury": "Lesión sin especificar",
    "hamstring injury": "Lesión de isquiotibiales",
    "muscle injury": "Lesión muscular",
    "muscular problems": "Molestias musculares",
    "ankle injury": "Lesión de tobillo",
    "knee injury": "Lesión de rodilla",
    "ill": "Enfermedad",
    "knock": "Golpe",
    "corona virus": "Coronavirus",
    "fitness": "Puesta a punto física",
    "calf injury": "Lesión de pantorrilla",
    "thigh problems": "Molestias en el muslo",
    "knee problems": "Molestias en la rodilla",
    "shoulder injury": "Lesión de hombro",
    "adductor pain": "Dolor en los aductores",
    "leg injury": "Lesión en la pierna",
    "cruciate ligament tear": "Rotura de ligamento cruzado",
    "groin injury": "Lesión de ingle",
    "foot injury": "Lesión de pie",
    "muscle fatigue": "Fatiga muscular",
    "ankle sprain": "Esguince de tobillo",
    "dead leg": "Contusión muscular en la pierna",
    "adductor injury": "Lesión de aductores",
    "minor knock": "Golpe leve",
    "flu": "Gripe",
    "ankle problems": "Molestias en el tobillo",
    "hamstring muscle injury": "Lesión muscular de isquiotibiales",
    "rest": "Descanso",
    "hamstring strain": "Distensión de isquiotibiales",
    "calf problems": "Molestias en la pantorrilla",
    "torn muscle fiber": "Rotura de fibras musculares",
    "quarantine": "Cuarentena",
    "hip injury": "Lesión de cadera",
    "injury to the ankle": "Lesión en el tobillo",
    "head injury": "Lesión en la cabeza",
    "back injury": "Lesión de espalda",
    "back problems": "Molestias en la espalda",
    "concussion": "Conmoción cerebral",
    "knee surgery": "Cirugía de rodilla",
    "bruise": "Contusión",
    "groin problems": "Molestias en la ingle",
    "cold": "Resfriado",
    "meniscus injury": "Lesión de menisco",
    "fever": "Fiebre",
    "stomach flu": "Gastroenteritis",
    "influenza": "Gripe",
    "inner ligament injury": "Lesión de ligamento interno",
    "metatarsal fracture": "Fractura de metatarso",
    "achilles tendon problems": "Molestias en el tendón de Aquiles",
    "muscle strain": "Distensión muscular",
    "ligament injury": "Lesión de ligamentos",
    "hip problems": "Molestias en la cadera",
    "strain": "Distensión",
    "ankle surgery": "Cirugía de tobillo",
    "virus": "Virus",
    "torn thigh muscle": "Rotura muscular en el muslo",
    "muscle tear": "Rotura muscular",
    "torn muscle bundle": "Rotura de fascículo muscular",
    "infection": "Infección",
    "injury to abdominal muscles": "Lesión en los músculos abdominales",
    "groin surgery": "Cirugía de ingle",
    "broken fibula": "Fractura de peroné",
    "surgery": "Cirugía",
    "foot bruise": "Contusión en el pie",
    "broken nose bone": "Fractura de nariz",
    "inflammation of pubic bone": "Inflamación del pubis",
    "meniscus tear": "Rotura de menisco",
    "toe injury": "Lesión en el dedo del pie",
    "knee bruise": "Contusión en la rodilla",
    "groin strain": "Distensión en la ingle",
    "broken foot": "Fractura de pie",
    "lumbago": "Lumbago",
    "torn ankle ligaments": "Rotura de ligamentos del tobillo",
    "syndesmotic ligament tear": "Rotura de sindesmosis",
    "pubalgia": "Pubalgia",
    "cruciate ligament injury": "Lesión de ligamento cruzado",
    "achilles tendon rupture": "Rotura del tendón de Aquiles",
    "calf muscle tear": "Rotura muscular en la pantorrilla",
    "bruised ribs": "Contusión en las costillas",
    "hand injury": "Lesión en la mano",
    "broken ankle": "Fractura de tobillo",
    "torn lateral knee ligament": "Rotura de ligamento lateral de la rodilla",
    "strain in the thigh and gluteal muscles": "Distensión en el muslo y los glúteos",
    "broken collarbone": "Fractura de clavícula",
    "bruised knee": "Contusión en la rodilla",
    "torn lateral ankle ligament": "Rotura de ligamento lateral del tobillo",
    "shin injury": "Lesión en la espinilla",
    "tonsillitis": "Amigdalitis",
    "appendectomy": "Apendicectomía",
    "heel problems": "Molestias en el talón",
    "pelvic injury": "Lesión pélvica",
    "broken toe": "Fractura de dedo del pie",
    "inner knee ligament tear": "Rotura de ligamento interno de la rodilla",
    "finger injury": "Lesión en el dedo de la mano",
    "chest injury": "Lesión en el pecho",
    "torn muscle fiber in the adductor area": "Rotura de fibras en los aductores",
    "capsular injury": "Lesión capsular",
    "broken cheekbone": "Fractura de pómulo",
    "broken hand": "Fractura de mano",
    "tendon rupture": "Rotura de tendón",
    "elbow injury": "Lesión en el codo",
    "inflammation": "Inflamación",
    "facial injury": "Lesión facial",
    "ligament stretching": "Estiramiento ligamentoso",
    "eye injury": "Lesión ocular",
    "collateral ligament injury": "Lesión de ligamento colateral",
    "outer ligament tear": "Rotura de ligamento externo",
    "sprain": "Esguince",
    "outer ligament problems": "Molestias en el ligamento externo",
    "internal ligament strain": "Distensión de ligamento interno",
    "stomach problems": "Molestias estomacales",
    "foot surgery": "Cirugía de pie",
    "calf strain": "Distensión en la pantorrilla",
    "muscle fiber tear": "Rotura de fibras musculares",
    "abdominal problems": "Molestias abdominales",
    "wrist injury": "Lesión en la muñeca",
    "knee medial ligament tear": "Rotura de ligamento medial de la rodilla",
    "hip flexor problems": "Molestias en el flexor de cadera",
    "metacarpal fracture": "Fractura de metacarpo",
    "abdominal muscle strain": "Distensión abdominal",
    "pubic bone irritation": "Irritación del pubis",
    "inguinal hernia": "Hernia inguinal",
    "cruciate ligament surgery": "Cirugía de ligamento cruzado",
    "broken arm": "Fractura de brazo",
    "contracture": "Contractura",
    "bruise on ankle": "Contusión en el tobillo",
    "heel injury": "Lesión en el talón",
    "syndesmosis ligament tear": "Rotura de sindesmosis",
    "arm injury": "Lesión en el brazo",
    "patellar tendon problems": "Molestias en el tendón rotuliano",
    "torn knee ligaments": "Rotura de ligamentos de la rodilla",
    "inner ligament stretch of the knee": "Estiramiento del ligamento interno de la rodilla",
    "partial muscle tear": "Rotura muscular parcial",
    "intestinal virus": "Virus intestinal",
    "ankle ligament tear": "Rotura de ligamento del tobillo",
    "achilles heel problems": "Molestias en el tendón de Aquiles",
    "muscle contusion": "Contusión muscular",
    "hip bruise": "Contusión en la cadera",
    "tendon tear": "Rotura de tendón",
    "broken jaw": "Fractura de mandíbula",
    "neck injury": "Lesión en el cuello",
    "heart problems": "Problemas cardíacos",
    "acromioclavicular joint dislocation": "Luxación acromioclavicular",
    "rib fracture": "Fractura de costilla",
    "tendon irritation": "Irritación tendinosa",
    "stress reaction of the bone": "Reacción de estrés óseo",
    "achilles tendon irritation": "Irritación del tendón de Aquiles",
    "dental surgery": "Cirugía dental",
    "bone edema": "Edema óseo",
    "tendonitis": "Tendinitis",
    "muscle stiffness": "Rigidez muscular",
    "broken leg": "Fractura de pierna",
    "scaphoid fracture": "Fractura de escafoides",
    "achilles tendon surgery": "Cirugía del tendón de Aquiles",
    "inflammation in the knee": "Inflamación en la rodilla",
    "broken finger": "Fractura de dedo de la mano",
    "right hip flexor problems": "Molestias en el flexor de cadera derecho",
    "achilles tendon contusion": "Contusión en el tendón de Aquiles",
    "flesh wound": "Herida abierta",
    "nose injury": "Lesión nasal",
    "metatarsal bruise": "Contusión en el metatarso",
    "bruise on the ankle joint": "Contusión en la articulación del tobillo",
    "wrist fracture": "Fractura de muñeca",
    "arthroscopy": "Artroscopia",
    "thumb injury": "Lesión en el pulgar",
    "mononucleation": "Mononucleosis",
    "edema in the knee": "Edema en la rodilla",
    "partial damage to the cruciate ligament": "Daño parcial del ligamento cruzado",
    "cartilage damage": "Daño en el cartílago",
    "fracture": "Fractura",
    "food poisoning": "Intoxicación alimentaria",
    "shin bruise": "Contusión en la espinilla",
    "patellar tendon rupture": "Rotura del tendón rotuliano",
    "pneumonia": "Neumonía",
    "sore muscles": "Molestias musculares",
    "pelvic contusion": "Contusión pélvica",
    "nose surgery": "Cirugía de nariz",
    "torn ligaments": "Rotura de ligamentos",
    "appendicitis": "Apendicitis",
    "arch problems": "Molestias en el arco del pie",
    "circulation problems": "Problemas circulatorios",
    "patellar tendon irritation": "Irritación del tendón rotuliano",
    "tibia and fibula fracture": "Fractura de tibia y peroné",
    "broken thumb": "Fractura de pulgar",
    "blockage in the back": "Bloqueo en la espalda",
    "facial fracture": "Fractura facial",
    "lumbar vertebra fracture": "Fractura de vértebra lumbar",
    "lumbar vertebra problems": "Molestias en vértebras lumbares",
    "tear of the lateral meniscus": "Rotura de menisco lateral",
    "meniscus damage": "Daño en el menisco",
    "laceration wound": "Herida por laceración",
    "angina": "Angina",
    "lymphatic cancer": "Cáncer linfático",
    "left hip flexor problems": "Molestias en el flexor de cadera izquierdo",
    "heel spur": "Espolón calcáneo",
    "eyebow fracture": "Fractura de ceja",
    "cut": "Corte",
    "overstretching": "Sobreestiramiento",
    "adductor tear": "Rotura de aductores",
    "fracture of fibula shaft": "Fractura de diáfisis del peroné",
    "broken tibia": "Fractura de tibia",
    "elbow fracture": "Fractura de codo",
    "fatigue fracture": "Fractura por fatiga",
    "herniated disc": "Hernia discal",
    "patellar tendon tear": "Rotura del tendón rotuliano",
    "inflammation in the head of the fibula": "Inflamación en la cabeza del peroné",
    "inflammation of the sole of the foot": "Inflamación en la planta del pie",
    "traffic accident": "Accidente de tráfico",
    "toothache": "Dolor de muelas",
    "cervical spine injury": "Lesión cervical",
    "dislocation of the kneecap": "Luxación de rótula",
    "bruised back": "Contusión en la espalda",
    "lower leg fracture": "Fractura en la parte baja de la pierna",
    "knee collateral ligament tear": "Rotura de ligamento colateral de la rodilla",
    "ruptured eardrum": "Rotura de tímpano",
    "hairline fracture in the fibula": "Fisura en el peroné",
    "testicle rupture": "Rotura testicular",
    "bone bruise": "Contusión ósea",
    "bronchitis": "Bronquitis",
    "ligament tear": "Rotura de ligamento",
    "contortion": "Torcedura",
    "partial tear of the plantar fascia": "Rotura parcial de fascia plantar",
    "fissure of the fibula": "Fisura de peroné",
    "patellar tendon dislocation": "Luxación del tendón rotuliano",
    "open wound": "Herida abierta",
    "pneumothorax": "Neumotórax",
    "cheekbone surgery": "Cirugía de pómulo",
    "scaphoid surgery": "Cirugía de escafoides",
    "fracture of the eye socket": "Fractura de órbita ocular",
    "bursitis": "Bursitis",
    "malaria": "Malaria",
    "knee collateral ligament strain": "Distensión de ligamento colateral de la rodilla",
    "shingles": "Herpes zóster",
    "vertebral injury": "Lesión vertebral",
    "toe joint capsular tear": "Rotura capsular en la articulación del dedo del pie",
    "partial patellar tendon tear": "Rotura parcial del tendón rotuliano",
    "inner ligament tear in ankle joint": "Rotura de ligamento interno del tobillo",
    "cruciate ligament strain": "Distensión de ligamento cruzado",
    "dislocation fracture of the ankle joint": "Fractura-luxación del tobillo",
    "inflammation of the biceps tendon in the thigh": "Inflamación del tendón del bíceps femoral",
    "broken shoulder": "Fractura de hombro",
    "vein occlusion": "Oclusión venosa",
    "pinched nerve": "Pinzamiento nervioso",
    "capsule rupture": "Rotura capsular",
    "collapsed lung": "Neumotórax",
    "whiplash": "Latigazo cervical",
    "laceration": "Laceración",
    "lung tear": "Desgarro pulmonar",
    "nerval disease": "Enfermedad nerviosa",
    "midfacial fracture": "Fractura del tercio medio facial",
    "bone inflammation": "Inflamación ósea",
    "overstretching of the syndesmotic ligament": "Sobreestiramiento de la sindesmosis",
    "hairline crack in foot": "Fisura en el pie",
    "neck bruise": "Contusión en el cuello",
    "patellar tendinopathy syndrome": "Tendinopatía rotuliana",
    "inner ankle ligament tear": "Rotura de ligamento interno del tobillo",
    "calf stiffness": "Rigidez en la pantorrilla",
    "cyst on jaw": "Quiste en la mandíbula",
    "depression": "Depresión",
    "internal ligament tear": "Rotura de ligamento interno",
    "testicular cancer": "Cáncer testicular",
    "inflammation in the spine": "Inflamación en la columna",
    "balance disorder": "Trastorno del equilibrio",
    "meningitis": "Meningitis",
    "abscess": "Absceso",
    "allergic reaction": "Reacción alérgica",
    "blood poisoning": "Septicemia",
    "bone marrow swelling": "Edema de médula ósea",
    "bone splintering": "Astillamiento óseo",
    "bone sprain": "Esguince óseo",
    "broken kneecap": "Fractura de rótula",
    "bruise on shinbone": "Contusión en la tibia",
    "cancer": "Cáncer",
    "capsular tear of ankle joint": "Rotura capsular del tobillo",
    "cervical vertebra fracture": "Fractura de vértebra cervical",
    "cheekbone bruise": "Contusión en el pómulo",
    "chickenpox": "Varicela",
    "collateral ligament tear": "Rotura de ligamento colateral",
    "compartment syndrome": "Síndrome compartimental",
    "compression of the spine": "Compresión de la columna",
    "cracked bone": "Fisura ósea",
    "cyst in the knee": "Quiste en la rodilla",
    "double ligament tear": "Rotura doble de ligamentos",
    "femoral fracture": "Fractura de fémur",
    "femoral neck fracture": "Fractura de cuello de fémur",
    "forearm fracture": "Fractura de antebrazo",
    "fracture of frontal bone": "Fractura del hueso frontal",
    "hairline fracture in the muscles": "Fisura muscular",
    "inflamed wound": "Herida infectada",
    "inflammation in the ankle joint": "Inflamación en la articulación del tobillo",
    "inflammation of ligaments in the knee": "Inflamación de ligamentos de la rodilla",
    "inflammation of the leg skin": "Inflamación de la piel de la pierna",
    "insect bite": "Picadura de insecto",
    "intestinal surgery": "Cirugía intestinal",
    "kidney problems": "Problemas renales",
    "longitudinal tendon tear": "Rotura longitudinal de tendón",
    "lung contusion": "Contusión pulmonar",
    "meniscus irritation": "Irritación de menisco",
    "pelvic obliquity": "Oblicuidad pélvica",
    "peroneus tendon injury": "Lesión del tendón peroneo",
    "pubic bone bruise": "Contusión en el pubis",
    "remove screws/nails": "Retiro de tornillos/clavos",
    "sciatica problems": "Ciática",
    "shoulder joint contusion": "Contusión en la articulación del hombro",
    "skin disease": "Enfermedad de la piel",
    "skull fracture": "Fractura de cráneo",
    "stroke": "Accidente cerebrovascular",
    "tibial head contusion": "Contusión en la meseta tibial",
    "tooth infection": "Infección dental",
}


def traducir_lesion(tipo_lesion):
    if not tipo_lesion:
        return None
    return TRADUCCION_LESION.get(tipo_lesion.strip().lower())
